name: CYRUS
favicon: null
layout_spectrum: 0.8940467017237097
typography_spectrum: 0.775448159314692
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.3642776142805815
  lightness: 0.05681146658025682
  saturation: 0.3569673798047006
  rhythmicContrast: 0.07856715423986316
purpose: []
