name: CYRUS
favicon: null
layout_spectrum: 0
typography_spectrum: 1
title: Cyrus Computer Consultants Ltd
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0153a1'
    - '#d9dfeb'
    - '#758fbb'
    - '#3b71ae'
    - '#fafaff'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
